import {
  Home as HomeIcon,
  MonitorCog as MonitorIcon,
  Code,
  FolderIcon,
  Package,
  ExternalLink,
  GithubIcon,
  Lightbulb,
  Languages,
  RouterIcon,
  Settings,
} from "lucide-react";
export const configSidebar = [
  {
    title: "Início",
    path: "/",
    Icon: HomeIcon,
    hasChildren: false,
    children: [],
  },
  {
    title: "Yo Liferay-js",
    path: "/yo-liferay-js",
    Icon: FolderIcon,
    hasChildren: true,
    children: [
      {
        external: false,
        title: "Config. Ambiente",
        path: "/yo-liferay-js",
        Icon: MonitorIcon,
        pathActive: "yo-liferay-js",
      },
      {
        external: false,
        title: "Módulo",
        path: "/yo-liferay-js/yo-modulo",
        Icon: Code,
        pathActive: "yo-liferay-js,yo-modulo",
      },
      {
        external: false,
        title: "Shared bundle",
        path: "/yo-liferay-js/yo-shared-bundle",
        Icon: Package,
        pathActive: "yo-liferay-js,yo-shared-bundle",
      },
      {
        external: true,
        title: "Documentação Oficial",
        path: "https://help.liferay.com/hc/pt/articles/360029147411-Installing-the-JS-Generator-and-Generating-a-Bundle",
        Icon: ExternalLink,
        pathActive: "external",
      },
    ],
  },
  {
    title: "Liferay CLI",
    path: "/liferay-cli",
    Icon: FolderIcon,
    hasChildren: true,
    children: [
      {
        external: false,
        title: "Config. Ambiente",
        path: "/liferay-cli",
        Icon: MonitorIcon,
        pathActive: "liferay-cli",
      },
      {
        external: false,
        title: "Módulo",
        path: "/liferay-cli/cli-modulo",
        Icon: Code,
        pathActive: "liferay-cli,cli-modulo",
      },
      {
        external: false,
        title: "Shared bundle",
        path: "/liferay-cli/cli-shared-bundle",
        Icon: Package,
        pathActive: "liferay-cli,cli-shared-bundle",
      },
      {
        external: true,
        title: "Documentação Oficial",
        path: "https://learn.liferay.com/w/dxp/liferay-development/tooling/other-tools/liferay-cli-tool",
        Icon: ExternalLink,
        pathActive: "external",
      },
    ],
  },
  {
    title: "Módulos",
    path: "/modulo",
    Icon: FolderIcon,
    hasChildren: true,
    children: [
      {
        external: false,
        title: "HashRouter",
        path: "/modulo/hash-router",
        Icon: RouterIcon,
        pathActive: "modulo,hash-router",
      },
      {
        external: false,
        title: "Configuration",
        path: "/modulo/configurations",
        Icon: Settings,
        pathActive: "modulo,configurations",
      },
      {
        external: false,
        title: "Languages",
        path: "/modulo/languages",
        Icon: Languages,
        pathActive: "modulo,languages",
      },
      {
        external: false,
        title: "Dicas",
        path: "/modulo/dicas",
        Icon: Lightbulb,
        pathActive: "modulo,dicas",
      },
    ],
  },
  {
    title: "Github",
    path: "https://github.com/Benhur-Silveira/liferay-doc",
    Icon: GithubIcon,
    external: true,
    hasChildren: false,
    children: [],
  },
];
